class CustomError1(Exception):

    def __init__(self):
        super().__init__('Error número 1')

class CustomError2(Exception):

    def __init__(self):
        super().__init__('Error número 2')

class CustomError3(Exception):

    def __init__(self):
        super().__init__('Error número 3')