from exceptions import CustomError1, CustomError2, CustomError3